//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.29 at 09:05:01 PM GMT+10:00 
//

package uts.wsd.teamtwo.JAXB;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "list"
})
@XmlRootElement(name = "hotels")
public class Hotels implements Serializable {

	@XmlElement(name="hotel")
    private ArrayList<Hotel> list = new ArrayList<Hotel>();
	
	public Hotels () { }
	
	public Hotels (ArrayList<Hotel> list)
	{
		this.list = list;
	}
	
	public Hotels filterById(int hotelId)
	{
		ArrayList<Hotel> filteredList = new ArrayList<Hotel>();
		for(Hotel hotel : list)
			if(hotel.getId() == hotelId)
			{
				filteredList.add(hotel);
				break;
			}
		
		return new Hotels(filteredList);
	}
	
	public Hotels filterByName(String name)
	{
		ArrayList<Hotel> filteredList = new ArrayList<Hotel>();
		for(Hotel hotel : list)
			if(hotel.getName().toLowerCase().contains(name.toLowerCase()))
				filteredList.add(hotel);
		
		return new Hotels(filteredList);
	}
	
	public Hotels filterByCountry(String country)
	{
		ArrayList<Hotel> filteredList = new ArrayList<Hotel>();
		for(Hotel hotel : list)
			if(hotel.getCountry().toLowerCase().equals(country.toLowerCase()))
				filteredList.add(hotel);
		
		return new Hotels(filteredList);
	}
	
	public Hotels filterByCity(String city)
	{
		ArrayList<Hotel> filteredList = new ArrayList<Hotel>();
		for(Hotel hotel : list)
			if(hotel.getCity().toLowerCase().equals(city.toLowerCase()))
				filteredList.add(hotel);
		
		return new Hotels(filteredList);
	}
	
	public Hotel getHotel(int hotelId)
	{
		for(Hotel hotel : list)
			if(hotel.getId() == hotelId)
				return hotel;
		return null;
	}

    public ArrayList<Hotel> getList()
    {
        return this.list;
    }
}
