//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.29 at 09:05:01 PM GMT+10:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uts.edu.au/31284/team2/wsd-hotels", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uts.wsd.teamtwo.JAXB;
